name: Release Container Image

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: parse version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF:11}
        MAJOR=$(echo "$VERSION" | cut -d . -f 1)
        MINOR=$(echo "$VERSION" | cut -d . -f 2)
        PATCH=$(echo "$VERSION" | cut -d . -f 3)
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "version_major=$MAJOR" >> $GITHUB_ENV
        echo "version_minor=$MINOR" >> $GITHUB_ENV
        echo "version_patch=$PATCH" >> $GITHUB_ENV
    
    - name: Log version
      run: |
        echo "Building version ${{ env.version }}"
        echo "Major: ${{ env.version_major }}, Minor: ${{ env.version_minor }}, Patch: ${{ env.version_patch }}"

    - name: Log in ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.F8_SECRET }}
    
    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push multi-arch image
      run: |
        IMG="ghcr.io/${{ github.repository }}"
        IMG=${IMG@L}

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag $IMG:${{ env.version }} \
          --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
          --tag $IMG:${{ env.version_major }}.latest \
          --tag $IMG:latest \
          --push .